AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to enable VPC Flowlogs and push logs to Cloudwatch'

Parameters:
  FlowlogName:
    Description: 'Name of the vpcflowlog'
    Type: String
    Default: 'VPC_Flowlog_cw'
  
  FlowlogFilter:
    Description: 'The type of traffic to capture (accepted traffic only, rejected traffic only, or all traffic)'
    Type: String
    AllowedValues:
    - ACCEPT
    - REJECT
    - ALL
  FlowlogIampolicy:
    Description: 'Name of the vpcflowlog'
    Type: String
    Default: 'Flowlog_policy'

  Cloudwatchloggroupname:
    Description: 'Name of the vpcflowlog'
    Type: String
    Default: 'VPC-Flowlogs' 
  MAI:
    Description: 'The maximum interval of time during which a flow of packets is captured and aggregated into a flow log record'
    Type: Number
    Default: 600
    AllowedValues: [60, 600]
  LogRetention:
    Description: 'retention period of logs in cloudwatch'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1096, 1827, 2192, 2557, 2922, 3288, 3653]

  FlowlogResourceType:
    Description: 'resource for which logs need to be enabled-subnet,transit gateway,vpc'
    Type: String
    Default: VPC
    AllowedValues: 
    - NetworkInterface
    - Subnet 
    - TransitGateway 
    - TransitGatewayAttachment 
    - VPC
    
  FlowLogDestinationType:
    Description: 'destination to push the logs'
    Type: String
    Default: cloud-watch-logs
    AllowedValues: 
    - cloud-watch-logs
    - kinesis-data-firehose
    - s3
  IAMRoleName:
    Description: 'Name of the Iam role'
    Type: String
    Default: 'VPC_Flowlog_Role'

  VPCID:
    Type: AWS::EC2::VPC::Id    

Resources:
  FlowlogLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref Cloudwatchloggroupname
      RetentionInDays: !Ref LogRetention
  FlowLogIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - vpc-flow-logs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Ref FlowlogIampolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                Resource: '*'
  
  VPCFlowlog:
    Type: AWS::EC2::FlowLog
    Properties: 
        ResourceId: !Ref VPCID
        ResourceType: !Ref FlowlogResourceType
        TrafficType: !Ref FlowlogFilter
        LogDestinationType: !Ref FlowLogDestinationType
        LogDestination: !GetAtt FlowlogLogGroup.Arn
        LogFormat: ${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start} ${end} ${action} ${log-status}
        MaxAggregationInterval: !Ref MAI
        DeliverLogsPermissionArn: !GetAtt FlowLogIAMRole.Arn
        Tags:
        - Key: Name
          Value: !Ref FlowlogName

Outputs:
  LogGroupName:
    Description: 'The name of the CloudWatch Logs log group where  publishes your flow logs.'
    Value: !Ref FlowlogLogGroup
  IAMROLEARN:
    Description: 'IAM Role ARN'
    Value: !GetAtt 'FlowLogIAMRole.Arn'

  CloudwatchloggroupARN:
    Description: 'Cloudwatch log group ARN'
    Value: !GetAtt 'FlowlogLogGroup.Arn'